services:
  db:
    image: postgres:16
    env_file:
      - .env
    networks:
      - backend
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backend: