"""Initial migration

Revision ID: 96749f3f4fbd
Revises:
Create Date: 2025-07-27 01:11:55.409248

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96749f3f4fbd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("records")
    # ### end Alembic commands ###
